version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - cd FeedBackApp
      - npm run build
  post_build:
    commands:
      - echo Build completed. Preparing to copy files to S3...
      - aws s3 sync dist/ s3://ajith-demo-s3-v1/ --delete
      - echo Files successfully uploaded to S3 bucket.

artifacts:
  files:
    - '**/*'
  base-directory: FeedBackApp/dist

cache:
  paths:
    - node_modules/**/*

